export { default as Navigation } from '../Navigation'
export { default as Hero } from '../Hero'
export { default as Features } from '../Features'
export { default as UseCases } from '../UseCases'
export { default as CTA } from '../CTA'
export { default as Footer } from '../Footer'